### ISSUE TITLE
Stack cards under draw pile so it's obvious it's a draw pile

### ISSUE THREAD

**Issue by Tyroche** [sternetj/shipwreck-arcana#7]

**Comment by sternetj** [comment]
Added some styles to differentiate the deck from the active cards
![image](https://user-images.githubusercontent.com/2295908/83878547-52453400-a70a-11ea-84c7-c2331d1da114.png)

The shadows indicate the existence of at least 3 cards in the deck but drop to one and none if there are two and one cards remaining in the deck respectively.

Fixed by b52d98d
